services:
  sip_service:
    environment:
    - SIP_PORT=4564
    - H323_PORT=9898
    - H323_ENABLED=false
    - SIP_ENABLED=false
    - PRIVATE_IP=192.168.7.526
    - PUBLIC_IP=203.0.113.2222
    - LICENCE_KEY_MANAGEMENT=12wssdfgrdghht#$%^GH%
    image: redis:latest
version: '3.8'
