services:
  voip_server:
    environment:
    - H323_ENABLED=false
    - SIP_ENABLED=false
    - H323_PORT=9898
    - SIP_PORT=4564
    - MAX_CONNECTIONS=100
    - LOG_LEVEL=debug
    - PRIVATE_IP=192.168.7.526
    - PUBLIC_IP=203.0.113.2222
    - LICENCE_KEY_MCU=saassaaasasasssaasaasasa
    image: voip_server:latest
    ports:
    - 6000:6000
    - 5060:5060
version: '3.8'
